tarantula.data.bucket.node=N01
tarantula.snowflake.node.number=1
tarantula.snowflake.epoch.start=2020,1,1

tarantula.member.discovery.kubernetes.enabled=true
tarantula.member.discovery.kubernetes.service.name=gameserver

tarantula.data.store.dir=/tarantula/data
tarantula.service.deployment.dir=/tarantula/deploy
tarantula.cluster.name.suffix=dev
tarantula.platform.cluster.initial.size=1
tarantula.auth.context=localhost
tarantula.service.push.address=127.0.0.1
tarantula.platform.cluster.backup.url=http://127.0.0.1:8090
tarantula.platform.cluster.backup.access.key=accesskey
tarantula.platform.cluster.backup.enabled=false