tarantula.data.bucket.group=BDS01
tarantula.data.bucket.node=ND01
tarantula.data.bucket.id=1
tarantula.cluster.name=tarantula-dev
tarantula.service.configuration.file=tarantula-service-view-config.xml
tarantula.auth.context=localhost
