spring.application.name=community
server.shutdown=graceful
spring.jpa.hibernate.ddl-auto=update

#POSTGRESQL
spring.datasource.url=jdbc:postgresql://192.168.1.11:5432/community
spring.datasource.username=postgres
spring.datasource.password=password

#H2 local sql
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:dcbapp
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.mvc.problemdetails.enabled=true

#logging ecs(json) | lagstash | gelf
#logging.structured.format.console=ecs
logging.level.root=INFO
logging.level.com.icodesoftware=TRACE

#logging.structured.format.file=ecs
#logging.file=[file_name]
#logging.path=[log_path]
