version: '3'

services:
  platform:
    container_name: platform
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8090:8090"
    volumes:
      - platform-data:/tarantula
      - ./config:/etc/tarantula
    restart: unless-stopped
    networks:
      - gamecluster-net

volumes:
  platform-data:

networks:
  gamecluster-net:
