#### BUILD
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml ./pom.xml
COPY modules ./modules
COPY platform ./platform
COPY load-test ./load-test
COPY udp-game-server ./udp-game-server

RUN mvn clean
RUN mvn clean install -DskipTests

#### PACKAGE
FROM gcr.io/distroless/java21:debug

COPY --from=build /app/platform/target/release/gec-platform-2.0-bin/gec-platform-2.0 /platform
COPY docker-entrypoint.sh /platform/bin/docker-entrypoint.sh
EXPOSE 8090

ENV USE_HOSTNAME=true

ENV TARANTULA_DATA_STORE_SIZE=2000
ENV TARANTULA_DATA_STORE_DIR=/tarantula/data
ENV TARANTULA_SERVICE_DEPLOY_DIR=/tarantula/deploy
ENV TARANTULA_AUTH_CONTEXT=localhost

ENV TARANTULA_KUBERNETES_ENABLED=false
ENV TARANTULA_KUBERNETES_NAME=gameserver

VOLUME /tarantula

WORKDIR /platform/bin

ENV JAVA_MEM_OPTS="-Xms2g -Xmx4g"

ENV JAVA_OPTS="-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"

ENTRYPOINT ["sh", "/platform/bin/docker-entrypoint.sh"]