game=earth8
batch=100
pool.size=8
scheduled.play=false
http.request.interval.ms=10
use.player.prefix=true
player.prefix=cake
host=http://10.0.0.20:8090
test.udp=false
udp.play.interval.ms=4000
udp.receive.timeout=3000
udp.test.rounds=10