#JDK Logging Configuration File
handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler
#handlers= java.util.logging.FileHandler
java.util.logging.FileHandler.pattern = %h/tarantula/log/tarantula-udp.log
java.util.logging.FileHandler.limit = 100000
java.util.logging.FileHandler.count = 10
java.util.logging.FileHandler.maxLocks = 100
java.util.logging.FileHandler.formatter = com.tarantula.integration.udp.JDKLoggingFormatter
java.util.logging.FileHandler.level = WARNING

java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = com.tarantula.integration.udp.JDKLoggingFormatter

