tarantula.data.bucket.group=BDS01
tarantula.data.bucket.node=ND01

tarantula.data.store.dir=/mnt/tds
tarantula.data.store.master=tarantula
tarantula.data.store.daily.backup=true
tarantula.data.store.recover.batch.size=100

tarantula.service.authenticator.provider=com.tarantula.platform.service.SystemValidatorProvider
tarantula.service.deployment.service.provider=com.tarantula.platform.service.deployment.PlatformDeploymentServiceProvider
tarantula.service.deployment.module.singleton.application=com.tarantula.platform.service.deployment.SingletonModuleApplication
tarantula.service.deployment.dir=/mnt/deploy

tarantula.endpoint.udp.pool.in.setting=udp-inbound,8,8,8,60,0
tarantula.endpoint.udp.enable=true

tarantula.endpoint.http=com.tarantula.cci.http.HttpEndpoint
tarantula.endpoint.http.port=8090
tarantula.endpoint.http.backlog=100
tarantula.endpoint.http.pool.in.setting=http-inbound,8,32,8,60,100

tarantula.endpoint.http.enable=true
tarantula.endpoint.session.timeout.m=100
tarantula.endpoint.ticket.timeout.s=10
tarantula.endpoint.session.max.number=10

tarantula.event.pool.setting=event,8,8,8,60,0
tarantula.event.max.retries=3
tarantula.event.retry.interval=10000

tarantula.data.replication.pool.setting=replication,8,8,8,60,0

tarantula.instance.session.idle.number=3
tarantula.instance.session.timeout.s=60
tarantula.lobby.subscription.enabled=false

tarantula.scheduler.pool.setting=scheduler,4,4

tarantula.operation.retries=3
tarantula.operation.reject.interval.ms=1000
tarantula.operation.metrics.interval.m=3
tarantula.operation.timeout.seconds=5
tarantula.cluster.name=tarantula
tarantula.platform.version=2.0
tarantula.platform.routing.number=17
tarantula.platform.access.index.routing.number=271
tarantula.member.discovery.name=com.tarantula.platform.service.cluster.StaticMemberDiscovery
