tarantula.data.bucket.group=BDS01
tarantula.data.bucket.node=ND01

tarantula.data.store.dir=/mnt/tds
tarantula.data.store.recovery.dir=/mnt/tmp
tarantula.data.store.master=tarantula
tarantula.data.store.daily.backup=true

tarantula.service.authenticator.provider=com.tarantula.platform.service.SystemValidatorProvider
tarantula.service.deployment.service.provider=com.tarantula.platform.service.deployment.PlatformDeploymentServiceProvider
tarantula.service.deployment.dir=/mnt/deploy
tarantula.endpoint.socket=com.tarantula.cci.tcp.SocketEndPoint
tarantula.endpoint.socket.port=6393
tarantula.endpoint.socket.backlog=100
tarantula.endpoint.socket.pool.in.setting=socket-inbound,8,8,8,60,0
tarantula.endpoint.socket.enable=true

tarantula.endpoint.http=com.tarantula.cci.http.HttpEndpoint
tarantula.endpoint.http.port=8090
tarantula.endpoint.http.backlog=100
tarantula.endpoint.http.pool.in.setting=http-inbound,8,32,8,60,100

tarantula.endpoint.http.enable=true
tarantula.endpoint.session.timeout.m=100
tarantula.endpoint.ticket.timeout.s=10
tarantula.endpoint.session.max.number=10

tarantula.event.pool.setting=event,12,12,12,60,0
tarantula.event.max.retries=3
tarantula.event.retry.interval=10000

tarantula.data.replication.pool.setting=replication,8,8,8,60,0

tarantula.instance.session.idle.number=3
tarantula.instance.session.timeout.s=60

tarantula.scheduler.pool.setting=scheduler,4,4

tarantula.operation.retries=3
tarantula.operation.reject.interval.ms=1000
tarantula.operation.metrics.interval.m=3
tarantula.cluster.name=tarantula
tarantula.deployment.mode=ALL
tarantula.bootstrap.max.retries=3
tarantula.platform.version=1.0
tarantula.platform.routing.number=7
tarantula.member.discovery.name=com.tarantula.platform.service.cluster.StaticMemberDiscovery
