tarantula.data.bucket.group=BDS
tarantula.data.bucket.node=N01
tarantula.data.store.size.mb=2000
tarantula.data.store.key.size=200
tarantula.data.store.value.size=1800
tarantula.data.store.pending.buffer.size=32
tarantula.data.store.no.sync=true
tarantula.data.store.dir=/var/tarantula/tds
tarantula.data.store.daily.backup=true
tarantula.data.store.recover.batch.size=100
tarantula.data.store.replication.max.number=3

tarantula.service.authenticator.provider=com.tarantula.platform.service.SystemValidatorProvider
tarantula.service.deployment.service.provider=com.tarantula.platform.service.deployment.PlatformDeploymentServiceProvider
tarantula.service.deployment.module.singleton.application=com.tarantula.platform.service.deployment.SingletonModuleApplication
tarantula.service.deployment.dir=/var/tarantula/deploy

tarantula.endpoint.udp.pool.in.setting=udp-messaging,8,8,8,30,0
tarantula.endpoint.udp.enable=true
tarantula.endpoint.udp=com.tarantula.cci.udp.UDPEndpoint
tarantula.endpoint.udp.port=11933

tarantula.endpoint.http=com.tarantula.cci.http.HttpEndpoint
tarantula.endpoint.http.port=8090
tarantula.endpoint.http.backlog=100
tarantula.endpoint.http.pool.in.setting=http-inbound,8,32,8,60,100

tarantula.endpoint.http.enable=true
tarantula.endpoint.session.timeout.m=1500
tarantula.endpoint.ticket.timeout.s=10
tarantula.endpoint.session.max.number=10

tarantula.event.pool.setting=event,8,8,8,60,0
tarantula.event.max.retries=3
tarantula.event.retry.interval=10000

tarantula.instance.session.idle.number=3
tarantula.instance.session.timeout.s=60
tarantula.lobby.subscription.enabled=false
tarantula.scheduler.pool.setting=scheduler,3,3

tarantula.operation.retries=3
tarantula.operation.reject.interval.ms=1000
tarantula.operation.timeout.seconds=5
tarantula.cluster.name.suffix=dev
tarantula.platform.routing.number=17
tarantula.platform.access.index.routing.number=271
tarantula.platform.cluster.initial.size=3
tarantula.platform.cluster.max.size=5
tarantula.platform.cluster.run.as.mirror=false
tarantula.platform.cluster.backup.enabled=false
tarantula.member.discovery.name=com.tarantula.platform.service.cluster.StaticMemberDiscovery
