batch=5000
pool.size=16
scheduled.play=true
http.request.interval.ms=1000
use.player.prefix=false
player.prefix=moon
host=http://192.168.1.9:8090
test.udp=true
udp.play.interval.ms=4000
udp.receive.timeout=3000
udp.test.rounds=100