package com.tarantula.platform.util;

import com.icodesoftware.protocol.PendingInboundMessage;
import com.icodesoftware.protocol.PendingOutboundMessage;
import com.icodesoftware.service.DeploymentServiceProvider;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.nio.ByteBuffer;
import java.security.Key;
import java.security.SecureRandom;
import java.util.Properties;
public class Email {

    public static void main(String[] args) throws Exception{
        //Email.send("yinghu_lu@hotmail.com","validation code: 4567");
        //SecretKey key = this.deploymentServiceProvider.serverKey();

        SecureRandom secureRandom = new SecureRandom();
        byte[] key = new byte[16];
        //byte[] iv = new byte[16];
        secureRandom.nextBytes(key);
        //secureRandom.nextBytes(iv);
        SecretKey skey = new SecretKeySpec(key, DeploymentServiceProvider.SERVER_KEY_SPEC);
        Cipher cipher = Cipher.getInstance(DeploymentServiceProvider.CIPHER_NAME_CBC_PKC5PADDING);
        cipher.init(Cipher.ENCRYPT_MODE,skey,new IvParameterSpec(key));
        PendingOutboundMessage out = new PendingOutboundMessage();
        out.ack(false);
        out.messageId(10);
        out.connectionId(100);
        out.type(10);
        ByteBuffer buffer = ByteBuffer.allocate(4);
        buffer.putInt(789);
        byte[] ret = cipher.doFinal(buffer.array());
        System.out.println(">>>"+ret.length);
        out.sequence(ret); //SEQ
        out.payload("TEST78889999999999999999999999999999999995".getBytes());
        PendingInboundMessage pendingInboundMessage = new PendingInboundMessage("sid",out.message(),null);
        System.out.println("ACK->"+pendingInboundMessage.ack());
        System.out.println("TYPE->"+pendingInboundMessage.type());
        Key skey2 = new SecretKeySpec(key, DeploymentServiceProvider.SERVER_KEY_SPEC);
        Cipher cipher1 = Cipher.getInstance(DeploymentServiceProvider.CIPHER_NAME_CBC_PKC5PADDING);
        System.out.println("block->"+cipher1.getBlockSize());
        IvParameterSpec ivc = new IvParameterSpec(key);
        cipher1.init(Cipher.DECRYPT_MODE,skey2,ivc);

        byte[] xret = cipher1.doFinal(pendingInboundMessage.sequence());
        System.out.println("MMMM-"+xret.length);
        ByteBuffer reb = ByteBuffer.allocate(4);
        reb.put(xret);
        System.out.println("SEQ->"+reb.getInt(0));
        System.out.println("MID->"+pendingInboundMessage.messageId());
        System.out.println("CID->"+pendingInboundMessage.connectionId());
        System.out.println("PAYLOAD->"+new String(pendingInboundMessage.payload()));


    }
    public static boolean send(String to,String text){

        //gmail test
        String from = "yinghu.lu@gmail.com";
        final String username = "yinghu.lu@gmail.com";//username generated by Mailtrap
        final String password = "X123!Y123";//password generated by Mailtrap
        String host = "smtp.gmail.com";
        Properties properties = new Properties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.ssl.enable", "true");
        properties.put("mail.smtp.auth", "true");

        Session session = Session.getInstance(properties,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipients(Message.RecipientType.TO,InternetAddress.parse(to));
            message.setSubject("Game Clustering Message");
            message.setText(text);
            Transport.send(message);
            return true;
        } catch (MessagingException e) {
            e.printStackTrace();
            return false;
        }
    }
}
