package com.tarantula.platform.util;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import java.util.Properties;
public class Email {

    public static void main(String[] args) throws Exception{
        //Email.send("yinghu_lu@hotmail.com","validation code: 4567");
    }
    public static boolean send(String to,String text){

        //gmail test
        String from = "yinghu.lu@gmail.com";
        final String username = "yinghu.lu@gmail.com";//username generated by Mailtrap
        final String password = "X123!Y123";//password generated by Mailtrap
        String host = "smtp.gmail.com";
        Properties properties = new Properties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.ssl.enable", "true");
        properties.put("mail.smtp.auth", "true");

        Session session = Session.getInstance(properties,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipients(Message.RecipientType.TO,InternetAddress.parse(to));
            message.setSubject("Game Clustering Message");
            message.setText(text);
            Transport.send(message);
            return true;
        } catch (MessagingException e) {
            e.printStackTrace();
            return false;
        }
    }
}
